# rebuild-review-index.ps1 -- regenerate review/index.html from manifest
# Called by publish-review.ps1 and close-review.ps1. Can be run standalone.

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path $PSScriptRoot -Parent
$ManifestPath = Join-Path $RepoRoot "review/.review-manifest.json"
$IndexPath = Join-Path $RepoRoot "review/index.html"

$manifest = if (Test-Path $ManifestPath) {
    @(Get-Content $ManifestPath -Raw | ConvertFrom-Json)
} else { @() }

# Active = not archived, not closed
$active = @($manifest | Where-Object { -not $_.archived -and -not $_.closed })
$today = Get-Date

$cards = ""
foreach ($item in $active) {
    $created = [datetime]::ParseExact($item.created, "yyyy-MM-dd", $null)
    $age = ($today - $created).Days
    $staleClass = if ($age -gt 10) { " stale" } else { "" }
    $dateLabel = "Created $($item.created)"
    if ($age -gt 13) { $dateLabel += " — auto-close pending" }
    $cards += @"

    <a class="review-card$staleClass" href="/review/$($item.slug)/">
      <div class="meta">
        <div class="title">$($item.title)</div>
        <div class="date">$dateLabel</div>
      </div>
      <div class="arrow"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 18l6-6-6-6"/></svg></div>
    </a>
"@
}

if (-not $cards) {
    $cards = '    <div class="empty">No active reviews.</div>'
}

$listBlock = "    <!-- generated by scripts/publish-review.ps1 -- do not edit by hand -->$cards"

$html = Get-Content $IndexPath -Raw -Encoding UTF8
$html = $html -replace '(?s)    <!-- generated.*?</div>(?=\s*</div>\s*</div>)', $listBlock
Set-Content $IndexPath $html -Encoding UTF8

Write-Host "review/index.html rebuilt ($($active.Count) active reviews)."
